// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Vivelab.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250716050422_v01")]
    partial class v01
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Vivelab.Modelos.Album", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Code"));

                    b.Property<int>("ArtistCode")
                        .HasColumnType("integer");

                    b.Property<string>("CoverUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Code");

                    b.HasIndex("ArtistCode");

                    b.ToTable("Albums");
                });

            modelBuilder.Entity("Vivelab.Modelos.Plan", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Code"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<int>("UserCount")
                        .HasColumnType("integer");

                    b.HasKey("Code");

                    b.ToTable("Plans");
                });

            modelBuilder.Entity("Vivelab.Modelos.Playlist", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Code"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserCode")
                        .HasColumnType("integer");

                    b.HasKey("Code");

                    b.HasIndex("UserCode");

                    b.ToTable("Playlists");
                });

            modelBuilder.Entity("Vivelab.Modelos.PlaylistSong", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Code"));

                    b.Property<int>("PlaylistCode")
                        .HasColumnType("integer");

                    b.Property<int>("SongCode")
                        .HasColumnType("integer");

                    b.HasKey("Code");

                    b.HasIndex("PlaylistCode");

                    b.HasIndex("SongCode");

                    b.ToTable("PlaylistSongs");
                });

            modelBuilder.Entity("Vivelab.Modelos.Song", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Code"));

                    b.Property<int?>("AlbumCode")
                        .HasColumnType("integer");

                    b.Property<int>("ArtistCode")
                        .HasColumnType("integer");

                    b.Property<string>("CoverUrl")
                        .HasColumnType("text");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalPlays")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Code");

                    b.HasIndex("AlbumCode");

                    b.HasIndex("ArtistCode");

                    b.ToTable("Songs");
                });

            modelBuilder.Entity("Vivelab.Modelos.Subscription", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Code"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PlanCode")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserCode")
                        .HasColumnType("integer");

                    b.HasKey("Code");

                    b.HasIndex("PlanCode");

                    b.HasIndex("UserCode")
                        .IsUnique();

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("Vivelab.Modelos.User", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Code"));

                    b.Property<double>("Balance")
                        .HasColumnType("double precision");

                    b.Property<string>("Bibliography")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Code");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Vivelab.Modelos.UserSubscription", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Code"));

                    b.Property<int>("SubscriptionCode")
                        .HasColumnType("integer");

                    b.Property<int>("UserCode")
                        .HasColumnType("integer");

                    b.HasKey("Code");

                    b.HasIndex("SubscriptionCode");

                    b.HasIndex("UserCode");

                    b.ToTable("UsersSubscriptions");
                });

            modelBuilder.Entity("Vivelab.Modelos.Album", b =>
                {
                    b.HasOne("Vivelab.Modelos.User", "Artist")
                        .WithMany("Albums")
                        .HasForeignKey("ArtistCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("Vivelab.Modelos.Playlist", b =>
                {
                    b.HasOne("Vivelab.Modelos.User", "User")
                        .WithMany("Playlists")
                        .HasForeignKey("UserCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Vivelab.Modelos.PlaylistSong", b =>
                {
                    b.HasOne("Vivelab.Modelos.Playlist", "Playlist")
                        .WithMany("PlaylistSongs")
                        .HasForeignKey("PlaylistCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vivelab.Modelos.Song", "Song")
                        .WithMany("PlayListsSongs")
                        .HasForeignKey("SongCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Playlist");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("Vivelab.Modelos.Song", b =>
                {
                    b.HasOne("Vivelab.Modelos.Album", "Album")
                        .WithMany("Songs")
                        .HasForeignKey("AlbumCode");

                    b.HasOne("Vivelab.Modelos.User", "Artist")
                        .WithMany("Songs")
                        .HasForeignKey("ArtistCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("Vivelab.Modelos.Subscription", b =>
                {
                    b.HasOne("Vivelab.Modelos.Plan", "Plan")
                        .WithMany("Subscriptions")
                        .HasForeignKey("PlanCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vivelab.Modelos.User", "PrimaryUser")
                        .WithOne("Subscription")
                        .HasForeignKey("Vivelab.Modelos.Subscription", "UserCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");

                    b.Navigation("PrimaryUser");
                });

            modelBuilder.Entity("Vivelab.Modelos.UserSubscription", b =>
                {
                    b.HasOne("Vivelab.Modelos.Subscription", "Subscription")
                        .WithMany("AdditionalUsers")
                        .HasForeignKey("SubscriptionCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vivelab.Modelos.User", "User")
                        .WithMany("UsersSubscriptions")
                        .HasForeignKey("UserCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscription");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Vivelab.Modelos.Album", b =>
                {
                    b.Navigation("Songs");
                });

            modelBuilder.Entity("Vivelab.Modelos.Plan", b =>
                {
                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("Vivelab.Modelos.Playlist", b =>
                {
                    b.Navigation("PlaylistSongs");
                });

            modelBuilder.Entity("Vivelab.Modelos.Song", b =>
                {
                    b.Navigation("PlayListsSongs");
                });

            modelBuilder.Entity("Vivelab.Modelos.Subscription", b =>
                {
                    b.Navigation("AdditionalUsers");
                });

            modelBuilder.Entity("Vivelab.Modelos.User", b =>
                {
                    b.Navigation("Albums");

                    b.Navigation("Playlists");

                    b.Navigation("Songs");

                    b.Navigation("Subscription");

                    b.Navigation("UsersSubscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
